# Generated by Django 4.0.5 on 2022-07-04 15:45

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='solution',
            name='submitted_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.FileField(upload_to=judge.models.TestCase.get_upload_path_inp),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.FileField(upload_to=judge.models.TestCase.get_upload_path_out),
        ),
    ]
